# Generated by Django 5.2.7 on 2025-12-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('info_officer', 'Information Officer')], default='patient', max_length=20),
        ),
    ]
