# Generated by Django 5.2.7 on 2025-12-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='uid',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True, unique=True),
        ),
    ]
