# Generated by Django 5.2.7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(help_text='e.g. 12 tablets')),
                ('dosage_frequency', models.CharField(
                    choices=[
                        ('once_daily', 'Once daily'),
                        ('twice_daily', 'Twice daily'),
                        ('every_8_hrs', 'Every 8 hours'),
                        ('every_night', 'Every night'),
                        ('every_morning', 'Every morning'),
                        ('every_12_hrs', 'Every 12 hours'),
                        ('every_6_hrs', 'Every 6 hours'),
                        ('three_times_daily', 'Three times daily'),
                        ('as_needed', 'As needed'),
                        ('weekly', 'Once weekly'),
                        ('other', 'Other'),
                    ],
                    max_length=30
                )),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='website.patientreport')),
            ],
        ),
    ]
